#!/usr/bin/env bash
# Script to clean generated leak_test.go files
set -euo pipefail

cd "$(dirname "$0")/.."

# Use process substitution to avoid subshell issues
while IFS= read -r f; do
	if grep -q "^// Code generated by \"scripts/gen_leak_tests.sh\"" "$f" 2>/dev/null; then
		rm "$f"
		echo "Removed: $f"
	fi
done < <(find . -name "leak_test.go" -type f 2>/dev/null || true)
