#!/usr/bin/env bash
# Script to generate leak_test.go files for packages without TestMain
set -euo pipefail

# Packages that already have TestMain in setup_test.go (use kvdb.RunTests)
PACKAGES_WITH_TESTMAIN="autopilot channeldb contractcourt graph/db graph invoices payments/db peer routing sweep"
LEAK_DENY_REGEX=${LEAK_DENY_REGEX:-'(^|/)(itest|lntest)(/|$)'}

cd "$(dirname "$0")/.."

# Track processed directories to avoid regenerating
declare -A processed_packages=()

# Find all packages with test files (whitespace-safe)
find . -name "*_test.go" -type f -print0 |
	while IFS= read -r -d '' test_file; do
		dir=$(dirname "$test_file")

		if [[ -n "${processed_packages[$dir]:-}" ]]; then
			continue
		fi
		processed_packages[$dir]=1

		# Skip if it's the lntest/leakcheck package itself
		if [[ "$dir" == *"lntest/leakcheck"* ]]; then
			continue
		fi

		# Get relative path without leading ./
		rel_dir="${dir#./}"

		# Skip vendor/.git or denylisted packages
		if [[ "$rel_dir" == vendor* ]] || [[ "$rel_dir" == .git* ]]; then
			continue
		fi
		if [[ "$rel_dir" =~ $LEAK_DENY_REGEX ]]; then
			continue
		fi

		# Skip packages that already have TestMain via known list
		skip=false
		for pkg in $PACKAGES_WITH_TESTMAIN; do
			if [[ "$rel_dir" == "$pkg" ]]; then
				skip=true
				break
			fi
		done

		if $skip; then
			continue
		fi

		# Check if package already has TestMain defined
		if grep -l "func TestMain" "$dir"/*_test.go 2>/dev/null | grep -q .; then
			continue
		fi

		# Get package name from existing test files (prefer non _test package).
		pkg_names=$(grep -h "^package " "$dir"/*_test.go 2>/dev/null | awk '{print $2}' | sort -u || true)
		if [[ -z "$pkg_names" ]]; then
			continue
		fi

		pkg_name=$(printf '%s\n' "$pkg_names" | awk '$0 !~ /_test$/ {print; exit}')
		if [[ -z "$pkg_name" ]]; then
			pkg_name=$(printf '%s\n' "$pkg_names" | head -1)
		fi

		# Generate leak_test.go
		cat >"$dir/leak_test.go" <<LEAKTESTEOF
// Code generated by "scripts/gen_leak_tests.sh". DO NOT EDIT.
// This file is auto-generated for goroutine leak detection.
//go:build goexperiment.goroutineleakprofile

package ${pkg_name}

import (
	"os"
	"testing"

	"github.com/lightningnetwork/lnd/lntest/leakcheck"
)

func TestMain(m *testing.M) {
	code := m.Run()

	// Check for goroutine leaks if the experiment is enabled.
	if leakErr := leakcheck.Check(); leakErr != nil {
		os.Stderr.WriteString("LEAK DETECTED: " + leakErr.Error() + "\n")
		code = 1
	}

	os.Exit(code)
}
LEAKTESTEOF
		echo "Generated: $dir/leak_test.go"
	done
